# Generated by Django 5.2.11 on 2026-03-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ads_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="price",
            field=models.IntegerField(
                blank=True, default=0, help_text="Укажите цену на товар", null=True, verbose_name="Цена на товар"
            ),
        ),
        migrations.AlterField(
            model_name="ads",
            name="title",
            field=models.CharField(
                help_text="Укажите наименование товара", max_length=100, null=True, verbose_name="Наименование товара"
            ),
        ),
    ]
