# Generated by Django 5.2.11 on 2026-03-13 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_ads_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="ad",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ads.ads", verbose_name="Объявление"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
