# Generated by Django 5.2.11 on 2026-03-13 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_alter_feedback_ad_alter_feedback_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.ads",
                verbose_name="Объявление",
            ),
        ),
    ]
