# Generated by Django 5.2.11 on 2026-03-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0006_alter_feedback_ad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ads",
            name="title",
        ),
    ]
