# Generated by Django 5.2.11 on 2026-03-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_remove_ads_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="ads",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Укажите наименование товара",
                max_length=100,
                null=True,
                verbose_name="Наименование товара",
            ),
        ),
    ]
